# Generated by Django 5.1.1 on 2024-09-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('director', models.CharField(max_length=30)),
                ('actors', models.TextField()),
                ('year', models.CharField(max_length=4)),
            ],
        ),
    ]
